name: Run Unit Tests

# run these unit tests on every push to the main branch and after a PR has been created
on:
  pull_request:
  push:
    branches:
      - main

# specify the environment variables that are usually in the ~/.databrickscfg file
env:
    DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
    DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
    DATABRICKS_SERVERLESS_COMPUTE_ID: auto

jobs:
  unit-test-notebook:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run unit tests
        run: |
          uv run pytest tests --cov=src
